### ISSUE TITLE
Fix log forging vunerabilities

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#50]
Fortify - validate input from main or dont use input from main in log statement

- [x] [ConfigurationLint.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationLint.java#L46) - Fixed in #469 (verify) 
- [x] [GraphDatabaseConfiguration.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java#L1374)
- [x] [GraphDatabaseConfiguration.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java#L1377)
- [x] [JanusGraphFactory](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java#L298) - Fixed in #469 (verify) 
- [x] [JanusGraphFactory](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java#L301) - Fixed in #469 (verify)
